name: boost Test

on: [push]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run clang-format"
        uses: DoozyX/clang-format-lint-action@v0.18.1
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: src
          build-dir: build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "ctest"
        run: ctest
        
#        run: clang-format -i src/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}